"""empty message

Revision ID: 0964727a3338
Revises: 88f8c4b5b978
Create Date: 2021-03-13 12:27:58.785762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0964727a3338'
down_revision = '88f8c4b5b978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('position_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='position_ibfk_1'),
    sa.PrimaryKeyConstraint('position_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
