"""empty message

Revision ID: 9566a2be4e64
Revises: 0964727a3338
Create Date: 2021-03-13 13:27:55.638995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9566a2be4e64'
down_revision = '0964727a3338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'position_id')
    # ### end Alembic commands ###
