"""empty message

Revision ID: a22adb6e6fd5
Revises: 9566a2be4e64
Create Date: 2021-03-13 15:34:02.299320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22adb6e6fd5'
down_revision = '9566a2be4e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'stages', ['stage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'stage_id')
    op.drop_table('stages')
    # ### end Alembic commands ###
